### ISSUE TITLE
Add Resume Theme

### ISSUE THREAD

**Issue by hishamco** [OrchardCoreContrib/OrchardCoreContrib.Themes#10]
https://startbootstrap.com/theme/resume

**Comment by Piedone** [comment]
Did you know that Antoine has such a theme too? https://github.com/agriffard/TheResumeTheme/

**Comment by hishamco** [comment]
Oh really, but seems doing it using Liquiq, I did it with Razor. My aim to publish few themes from the first day I created the repo just one contributor created one theme.

Just struggling to add more themes from startbootstrap, thanks for mentioning this
